#=========================
# ---- Aláírt szkript ----
#=========================
Write-Host "Hello World!"
# ------------------------
# SIG # Begin signature block
# MIIFZwYJKoZIhvcNAQcCoIIFWDCCBVQCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUNg5y7vbxjSsBwQgSpjpRDhR2
# 6pmgggMNMIIDCTCCAfGgAwIBAgIQGZt+qk/knZNEaU8ExvIMRzANBgkqhkiG9w0B
# AQsFADAPMQ0wCwYDVQQDDARVc2VyMB4XDTIyMDExMjE3MjkwNFoXDTIzMDExMjE3
# NDkwNFowDzENMAsGA1UEAwwEVXNlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
# AQoCggEBAOUZZA5CfIjiusf6z8m2my/qWrSymSsV0mH+pzQgP+ol6S1dLpOJ0XBD
# yz5tQj03poInhqxr6gR3HJn4H1YOaQaPBgAKJtWBA356hGSLSq7egxmcy/llL+HW
# WDruIWbFadI6xvn7CAgk9+Qk6Vc1FK1ez64cmgn0vdKI7QHj0EzgDNjrYGI1UoGS
# 9g/3LU4XHiSNWA+37Lb/3+SQdFnrUMGOVabbrrU3kW2QhbYMVZF0/Q6ngV7/l7eO
# Ze87XzO2HcoBM2lIqs0iyZryXz/NNguqW+TUGv0Wc6gUvA8DC65K7ubS7hueih65
# Lfb4OabcwXTqt53vaNS3eyPuEDaeSnUCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgeA
# MBMGA1UdJQQMMAoGCCsGAQUFBwMDMBkGA1UdEQQSMBCCDlRyYWluaW5nU2VydmVy
# MB0GA1UdDgQWBBRaUqWzHRlUiAL12t/HiIcI+fPjyzANBgkqhkiG9w0BAQsFAAOC
# AQEAzhCo+JCM3x02shCNcpdT6MlsauJw/D/If3dIji9C1RIvEy9C6hSq2LyybRKd
# 55MUgdeaGNtgdcL6lCewULrEGBfQQyhtathwUzYKl05+G07X/OH+c6qk3TTpDcTj
# Ph7ZRbClDfHMO2lan5X889XO0meAGahYNdAprYkFDr13dmKhhSmp5Z88a356hQzB
# YRRpklo8leDik45FaYh+B4T/Mgt1ifFY+qf1snilJGm3kKwVd2op+mGRfoPGCJz0
# KahY/v7FXlHwSasjjhyqMyn/Y47091sCEZb2L6TS8exRI8T/OPZo6boFJVRoI1K3
# /9WlbYvkPrd3B/BEqpNzHWummDGCAcQwggHAAgEBMCMwDzENMAsGA1UEAwwEVXNl
# cgIQGZt+qk/knZNEaU8ExvIMRzAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEK
# MAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3
# AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUhDePRykYbNkKzmQw
# 65RV/B1TxiEwDQYJKoZIhvcNAQEBBQAEggEAb91YU9oJcCk6TH09mBbnx2fvAP3a
# 1lk9Meso5PXXDH7IEMoxUeAcgJILAPBPhE4cnIk/sJUeK1Gt+ZzdpQvW8uoimyL6
# MhciyXbZeCwhCjS2O3qNx/Ph7QKcLWujUgqirXNAB/PNG5wDEA0o0Ow9y6r/P5ur
# Td7AGPZcFdiu4mQwSx8DO29G5D1ghxPCeWWwJR+A2rEacZQHMqjdrnL1m3jmW88s
# peHxu8PilA69XG5AU0+8J5kWyIZcfvvtlwQljaXki2a7ETHzNZzKy9uX3fjxryxQ
# GB3CoOZ+Z+rlrAD8RNZtZdFjnB4Fb8QiAppKlZIueutDq/ANx+qcNNZxzg==
# SIG # End signature block
